from datetime import datetime

from sqlalchemy import (
    JSON,
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.core.db import Base
from app.models.base import IntegerPkMixin, TimestampMixin

EMAIL_DELIVERY_STATUSES = ("pending", "sending", "sent", "failed")


class EmailTemplate(IntegerPkMixin, TimestampMixin, Base):
    """Editable human-readable content of an institutional email.

    The HTML shell is generated by the renderer; staff never edit markup.
    """

    __tablename__ = "email_templates"

    template_key: Mapped[str] = mapped_column(String(80), unique=True, index=True)
    name: Mapped[str] = mapped_column(String(180))
    subject_template: Mapped[str] = mapped_column(String(300))
    body_template: Mapped[str] = mapped_column(Text)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)


class EmailDelivery(IntegerPkMixin, TimestampMixin, Base):
    """Auditable record of one outgoing message; snapshots are deliberate.

    ``sent`` means the SMTP relay accepted the message, nothing more. Secret
    variables (tokens, links) are redacted in the stored snapshots.
    """

    __tablename__ = "email_deliveries"
    __table_args__ = (
        CheckConstraint(
            "status IN ('pending', 'sending', 'sent', 'failed')",
            name="ck_email_deliveries_status",
        ),
        Index("ix_email_deliveries_related_entity", "related_entity_type", "related_entity_id"),
    )

    template_key: Mapped[str] = mapped_column(String(80), index=True)
    related_entity_type: Mapped[str | None] = mapped_column(String(60))
    related_entity_id: Mapped[int | None] = mapped_column(Integer)
    to_json: Mapped[list] = mapped_column(JSON, default=list)
    cc_json: Mapped[list] = mapped_column(JSON, default=list)
    bcc_json: Mapped[list] = mapped_column(JSON, default=list)
    subject: Mapped[str] = mapped_column(String(300))
    body_text_snapshot: Mapped[str] = mapped_column(Text)
    body_html_snapshot: Mapped[str] = mapped_column(Text)
    attachments_json: Mapped[list] = mapped_column(JSON, default=list)
    status: Mapped[str] = mapped_column(String(20), default="pending", index=True)
    attempt_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    provider_message_id: Mapped[str | None] = mapped_column(String(255))
    provider_response: Mapped[str | None] = mapped_column(Text)
    last_error: Mapped[str | None] = mapped_column(Text)
    # Machine-readable reason of the last failure (e.g. "email_disabled").
    failure_code: Mapped[str | None] = mapped_column(String(40))
    requested_by_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), index=True
    )
    sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    failed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
