import React, { useEffect, useMemo, useState } from 'react';

import {
  approvePortalLinkRequest, cancelPortalInvitation, cancelPortalLinkRequest, createPortalInvitation, createPortalLinkRequest,
  getPortalConfiguration, listClients, listPortalInvitations, listPortalLinkRequests, listPortalMemberships, listPortalRegistrations, listPortalRoles,
  reactivatePortalMembership, rejectPortalLinkRequest, resendPortalInvitation, reviewPortalLinkRequest, revokePortalInvitation, revokePortalMembership,
  savePortalConfiguration, setPrimaryPortalMembership, suspendPortalMembership, updatePortalMembershipRoles
} from '../../services/api.js';

const DEFAULT_CONFIG = { display_name: null, primary_color: '#0F766E', language: 'es-MX', timezone: 'America/Mexico_City', default_home_page: 'dashboard', welcome_message: null, allow_self_registration: true, allow_invitations: true, require_mfa: false, session_timeout_minutes: 480, password_expiration_days: null, email_notifications_enabled: true, is_enabled: true, logo_path: null };

function MultiRolePicker({ roles, value, onChange }) {
  return <div className="settings-role-checklist settings-role-checklist--compact">{roles.map((role) => <label className="settings-checkbox" key={role.id}><input checked={value.includes(role.code)} onChange={() => onChange(value.includes(role.code) ? value.filter((code) => code !== role.code) : [...value, role.code])} type="checkbox" /><span><strong>{role.name}</strong><small>{role.permission_codes?.join(', ')}</small></span></label>)}</div>;
}

export default function PortalAccessSettingsPanel({ initialClientId = null, onChanged = null }) {
  const [section, setSection] = useState('memberships'); const [clients, setClients] = useState([]); const [clientId, setClientId] = useState(initialClientId ? String(initialClientId) : '');
  const [memberships, setMemberships] = useState([]); const [invitations, setInvitations] = useState([]); const [registrations, setRegistrations] = useState([]); const [requests, setRequests] = useState([]); const [roles, setRoles] = useState([]);
  const [invite, setInvite] = useState({ email: '', full_name: '', role_codes: ['viewer'], notes: '' }); const [link, setLink] = useState({ registration_id: '', reason: '' }); const [resolution, setResolution] = useState({ request_id: null, reason: '', role_codes: ['viewer'] });
  const [config, setConfig] = useState(DEFAULT_CONFIG); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const client = clients.find((item) => item.id === Number(clientId));

  async function loadGlobal() {
    try {
      const [clientItems, registrationItems, requestItems] = await Promise.all([listClients({ includeInactive: false }), listPortalRegistrations(), listPortalLinkRequests()]);
      setClients(clientItems); setRegistrations(registrationItems); setRequests(requestItems);
      setError('');
      if (!clientId && clientItems[0]) setClientId(String(clientItems[0].id));
    } catch (requestError) { setError(requestError.message); }
  }
  async function loadClient() {
    if (!clientId) return;
    try {
      const [membershipItems, invitationItems, roleItems] = await Promise.all([listPortalMemberships(clientId), listPortalInvitations(clientId), listPortalRoles(clientId)]);
      setMemberships(membershipItems); setInvitations(invitationItems); setRoles(roleItems);
      try { setConfig(await getPortalConfiguration(clientId)); } catch { setConfig(DEFAULT_CONFIG); }
      setError('');
    } catch (requestError) { setError(requestError.message); }
  }
  useEffect(() => { loadGlobal(); }, []);
  useEffect(() => { loadClient(); }, [clientId]);

  async function action(work, success) { setBusy(true); setError(''); setNotice(''); try { const result = await work(); setNotice(typeof success === 'function' ? success(result) : success); await Promise.all([loadGlobal(), loadClient()]); onChanged?.(); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } }
  async function submitInvite(event) { event.preventDefault(); if (!invite.role_codes.length) return setError('Selecciona al menos un rol.'); return action(async () => { const created = await createPortalInvitation({ client_id: Number(clientId), email: invite.email, full_name: invite.full_name || null, role_codes: invite.role_codes, notes: invite.notes || null }); setInvite({ email: '', full_name: '', role_codes: ['viewer'], notes: '' }); return created; }, (created) => created.invitation_url ? `Invitación creada; enlace de desarrollo: ${created.invitation_url}` : 'Invitación creada y enviada.'); }
  async function submitLink(event) { event.preventDefault(); return action(() => createPortalLinkRequest({ registration_id: Number(link.registration_id), client_id: Number(clientId), reason: link.reason || null }), 'Solicitud de vinculación creada.'); }
  async function resolve(requestId, approve) { if (!resolution.reason.trim()) return setError('Captura una resolución.'); if (approve && !resolution.role_codes.length) return setError('Selecciona al menos un rol.'); return action(() => approve ? approvePortalLinkRequest(requestId, resolution) : rejectPortalLinkRequest(requestId, resolution), approve ? 'Solicitud aprobada y membresía creada.' : 'Solicitud rechazada sin crear membresía.'); }
  async function saveConfig(event) { event.preventDefault(); const payload = { ...config, logo_path: null, password_expiration_days: config.password_expiration_days ? Number(config.password_expiration_days) : null, session_timeout_minutes: Number(config.session_timeout_minutes), require_mfa: false }; return action(() => savePortalConfiguration(clientId, payload), 'Configuración del portal guardada.'); }

  const pendingRegistrations = registrations.filter((item) => item.status !== 'linked');
  const clientRequests = requests.filter((item) => item.proposed_client_id === Number(clientId));
  const effective = useMemo(() => new Map(roles.map((role) => [role.code, role])), [roles]);
  return <section className="settings-panel portal-access-manager">
    <div className="section-heading"><div><p>Usuarios externos</p><h2>Portal del Cliente y MYC Mobile</h2><small>Los perfiles externos se asignan a la membresía del cliente; nunca como roles internos MYC.</small></div><select className="settings-role-select" onChange={(event) => setClientId(event.target.value)} value={clientId}>{clients.map((item) => <option key={item.id} value={item.id}>{item.commercial_name || item.legal_name}</option>)}</select></div>
    {client ? <div className="portal-client-comparison"><span><small>Razón social</small><strong>{client.legal_name}</strong></span><span><small>Nombre comercial</small><strong>{client.commercial_name || 'Sin nombre comercial'}</strong></span><span><small>RFC</small><strong>{client.rfc || 'Sin RFC'}</strong></span><span><small>Dominio / correo</small><strong>{client.email || 'Sin correo'}</strong></span><span><small>Contactos</small><strong>{client.contacts?.map((contact) => contact.name).join(', ') || 'Sin contactos'}</strong></span></div> : null}
    {error ? <div className="form-error">{error}</div> : null}{notice ? <div className="form-notice">{notice}</div> : null}
    <div className="portal-summary-grid"><article className="portal-summary-card"><span className="portal-summary-card__body"><small>Cuentas activas</small><strong>{memberships.filter((item) => item.status === 'active').length}</strong></span></article><article className="portal-summary-card"><span className="portal-summary-card__body"><small>Cuentas suspendidas</small><strong>{memberships.filter((item) => item.status === 'suspended').length}</strong></span></article><article className="portal-summary-card"><span className="portal-summary-card__body"><small>Invitaciones pendientes</small><strong>{invitations.filter((item) => item.status === 'pending').length}</strong></span></article><article className="portal-summary-card portal-summary-card--global"><span className="portal-summary-card__body"><small>Registros públicos globales</small><strong>{pendingRegistrations.length}</strong><em>No se atribuyen al cliente seleccionado</em></span></article></div>
    <div className="client-modal-tabs portal-operation-tabs">{[['memberships','Cuentas'],['registrations','Registros públicos'],['requests','Solicitudes'],['invitations','Invitaciones'],['configuration','Configuración']].map(([value,label]) => <button className={section === value ? 'client-modal-tab is-active' : 'client-modal-tab'} key={value} onClick={() => setSection(value)} type="button">{label}</button>)}</div>

    {section === 'memberships' ? <div className="portal-operation-list">{memberships.map((item) => <article className="portal-operation-card" key={item.id}><div><strong>{item.full_name}{item.is_primary_contact ? ' · Contacto principal' : ''}</strong><span>{item.email} · {item.status} · origen: {item.source}</span><div className="settings-chip-list">{item.role_codes.map((code) => <span key={code}>{effective.get(code)?.name || code}</span>)}</div></div><details><summary>Administrar acceso</summary><MultiRolePicker onChange={(codes) => action(() => updatePortalMembershipRoles(item.id, codes), 'Roles actualizados.')} roles={roles} value={item.role_codes} /><div className="settings-inline-actions"><button disabled={busy || item.is_primary_contact} onClick={() => action(() => setPrimaryPortalMembership(item.id), 'Contacto principal actualizado.')} type="button">Marcar principal</button>{item.status === 'active' ? <button onClick={() => action(() => suspendPortalMembership(item.id, 'Suspensión administrativa'), 'Membresía suspendida.')} type="button">Suspender</button> : <button onClick={() => action(() => reactivatePortalMembership(item.id), 'Membresía reactivada.')} type="button">Reactivar</button>}<button className="danger-text" onClick={() => action(() => revokePortalMembership(item.id, 'Revocación administrativa'), 'Membresía revocada.')} type="button">Revocar</button></div></details></article>)}{!memberships.length ? <div className="clients-empty">Este cliente todavía no tiene cuentas vinculadas.</div> : null}</div> : null}

    {section === 'registrations' ? <><form className="portal-operation-form" onSubmit={submitLink}><label>Registro público<select required value={link.registration_id} onChange={(event) => setLink((current) => ({ ...current, registration_id: event.target.value }))}><option value="">Seleccionar registro</option>{pendingRegistrations.map((item) => <option key={item.id} value={item.id}>{item.user.full_name} · {item.declared_company_name}</option>)}</select></label><label>Justificación<textarea required value={link.reason} onChange={(event) => setLink((current) => ({ ...current, reason: event.target.value }))} /></label><button className="primary-button" disabled={busy} type="submit">Crear solicitud para este cliente</button></form><div className="portal-operation-list">{pendingRegistrations.map((item) => <article className="portal-operation-card" key={item.id}><div><strong>{item.user.full_name} · @{item.user.username}</strong><span>{item.user.email} · {item.declared_company_name} · RFC {item.declared_company_rfc || 'no declarado'}</span><small>{item.email_verified_at ? 'Correo verificado' : 'Correo pendiente'} · {new Date(item.created_at).toLocaleString()}</small></div><span className="settings-status inactive">{item.status}</span></article>)}</div></> : null}

    {section === 'requests' ? <div className="portal-operation-list">{clientRequests.map((item) => <article className="portal-operation-card" key={item.id}><div><strong>{item.registration_full_name} · {item.declared_company_name}</strong><span>Propuesto: {item.proposed_client_name} · solicitado por {item.requested_by_name}</span><p>{item.request_reason || 'Sin justificación'}</p><small>{item.status} · {new Date(item.created_at).toLocaleString()}</small></div><details open={resolution.request_id === item.id}><summary onClick={() => setResolution((current) => ({ ...current, request_id: item.id }))}>Revisar solicitud</summary>{item.status === 'pending' ? <button onClick={() => action(() => reviewPortalLinkRequest(item.id), 'Solicitud tomada para revisión.')} type="button">Tomar para revisión</button> : null}{['pending','under_review'].includes(item.status) ? <><textarea placeholder="Resolución" value={resolution.request_id === item.id ? resolution.reason : ''} onChange={(event) => setResolution((current) => ({ ...current, request_id: item.id, reason: event.target.value }))} /><MultiRolePicker roles={roles} value={resolution.role_codes} onChange={(codes) => setResolution((current) => ({ ...current, request_id: item.id, role_codes: codes }))} /><div className="settings-inline-actions"><button onClick={() => resolve(item.id, true)} type="button">Aprobar y vincular</button><button onClick={() => resolve(item.id, false)} type="button">Rechazar</button><button onClick={() => action(() => cancelPortalLinkRequest(item.id, resolution.reason || null), 'Solicitud cancelada.')} type="button">Cancelar</button></div></> : <p>{item.resolution_reason || 'Sin resolución capturada'}</p>}</details></article>)}{!clientRequests.length ? <div className="clients-empty">No hay solicitudes para el cliente seleccionado.</div> : null}</div> : null}

    {section === 'invitations' ? <><form className="portal-operation-form" onSubmit={submitInvite}><label>Correo<input required type="email" value={invite.email} onChange={(event) => setInvite((current) => ({ ...current, email: event.target.value }))} /></label><label>Nombre opcional<input value={invite.full_name} onChange={(event) => setInvite((current) => ({ ...current, full_name: event.target.value }))} /></label><label>Notas<textarea value={invite.notes} onChange={(event) => setInvite((current) => ({ ...current, notes: event.target.value }))} /></label><MultiRolePicker roles={roles} value={invite.role_codes} onChange={(codes) => setInvite((current) => ({ ...current, role_codes: codes }))} /><button className="primary-button" disabled={busy || !config.allow_invitations} type="submit">Invitar cuenta</button>{!config.allow_invitations ? <small>Las invitaciones están deshabilitadas en la configuración.</small> : null}</form><div className="portal-operation-list">{invitations.map((item) => <article className="portal-operation-card" key={item.id}><div><strong>{item.full_name || item.email}</strong><span>{item.email} · {item.role_codes.join(', ')}</span><small>{item.status} · creada {new Date(item.created_at).toLocaleString()} · vence {new Date(item.expires_at).toLocaleString()}</small></div>{item.status === 'pending' ? <div className="settings-inline-actions"><button onClick={() => action(() => resendPortalInvitation(item.id), 'Invitación reenviada.')} type="button">Reenviar</button><button onClick={() => action(() => cancelPortalInvitation(item.id), 'Invitación cancelada.')} type="button">Cancelar</button><button onClick={() => action(() => revokePortalInvitation(item.id), 'Invitación revocada.')} type="button">Revocar</button></div> : null}</article>)}</div></> : null}

    {section === 'configuration' ? <form className="portal-configuration-form" onSubmit={saveConfig}><label>Nombre visible<input value={config.display_name || ''} onChange={(event) => setConfig((current) => ({ ...current, display_name: event.target.value || null }))} /></label><label>Color primario<input pattern="#[0-9A-Fa-f]{6}" value={config.primary_color || ''} onChange={(event) => setConfig((current) => ({ ...current, primary_color: event.target.value || null }))} /></label><label>Idioma<select value={config.language} onChange={(event) => setConfig((current) => ({ ...current, language: event.target.value }))}><option value="es-MX">Español (México)</option><option value="en-US">English (US)</option></select></label><label>Zona horaria<input value={config.timezone} onChange={(event) => setConfig((current) => ({ ...current, timezone: event.target.value }))} /></label><label>Página inicial<input value={config.default_home_page} onChange={(event) => setConfig((current) => ({ ...current, default_home_page: event.target.value }))} /></label><label>Tiempo de sesión (min)<input max="1440" min="15" type="number" value={config.session_timeout_minutes} onChange={(event) => setConfig((current) => ({ ...current, session_timeout_minutes: event.target.value }))} /></label><label>Expiración de contraseña (días)<input min="1" type="number" value={config.password_expiration_days || ''} onChange={(event) => setConfig((current) => ({ ...current, password_expiration_days: event.target.value }))} /></label><label className="form-field--wide">Mensaje de bienvenida<textarea value={config.welcome_message || ''} onChange={(event) => setConfig((current) => ({ ...current, welcome_message: event.target.value || null }))} /></label>{[['is_enabled','Portal habilitado'],['allow_self_registration','Permitir autorregistro'],['allow_invitations','Permitir invitaciones'],['email_notifications_enabled','Notificaciones por correo']].map(([key,label]) => <label className="settings-checkbox" key={key}><input checked={Boolean(config[key])} onChange={(event) => setConfig((current) => ({ ...current, [key]: event.target.checked }))} type="checkbox" />{label}</label>)}<label className="settings-checkbox is-disabled"><input checked={false} disabled type="checkbox" />MFA (no disponible)</label><p className="form-field--wide settings-tab-help">La carga de logotipo no se muestra porque el backend sólo conserva una ruta de texto; no se simula una subida.</p><button className="primary-button" disabled={busy} type="submit">Guardar configuración</button></form> : null}
  </section>;
}
