import React, { useEffect, useState } from 'react';
import { createPortalInvitation, listClients, listPortalInvitations, listPortalMemberships, listPortalRegistrations, listPortalRoles } from '../../services/api.js';

export default function PortalAccessSettingsPanel() {
  const [clients, setClients] = useState([]); const [clientId, setClientId] = useState('');
  const [memberships, setMemberships] = useState([]); const [invitations, setInvitations] = useState([]); const [registrations, setRegistrations] = useState([]); const [roles, setRoles] = useState([]);
  const [form, setForm] = useState({ email: '', full_name: '', role_code: 'viewer' }); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { listClients({ includeInactive: false }).then((items) => { setClients(items); if (items[0]) setClientId(String(items[0].id)); }).catch((e) => setError(e.message)); listPortalRegistrations().then(setRegistrations).catch(() => {}); }, []);
  useEffect(() => { if (!clientId) return; Promise.all([listPortalMemberships(clientId), listPortalInvitations(clientId), listPortalRoles(clientId)]).then(([m, i, r]) => { setMemberships(m); setInvitations(i); setRoles(r); }).catch((e) => setError(e.message)); }, [clientId]);
  async function invite(event) { event.preventDefault(); setError(''); try { const created = await createPortalInvitation({ client_id: Number(clientId), email: form.email, full_name: form.full_name || null, role_codes: [form.role_code], notes: null }); setInvitations((items) => [created, ...items]); setNotice(created.invitation_url ? `Invitación creada: ${created.invitation_url}` : 'Invitación creada y enviada.'); setForm((v) => ({ ...v, email: '', full_name: '' })); } catch (e) { setError(e.message); } }
  return <section className="settings-panel"><div className="section-heading"><div><p>Portal del Cliente</p><h2>Accesos y solicitudes</h2></div><select className="settings-role-select" value={clientId} onChange={(e) => setClientId(e.target.value)}>{clients.map((client) => <option key={client.id} value={client.id}>{client.commercial_name || client.legal_name}</option>)}</select></div>{error ? <div className="form-error">{error}</div> : null}{notice ? <div className="form-notice">{notice}</div> : null}<form className="settings-user-form" onSubmit={invite}><label className="field-label">Correo<input className="text-input" type="email" required value={form.email} onChange={(e) => setForm((v) => ({ ...v, email: e.target.value }))} /></label><label className="field-label">Nombre<input className="text-input" value={form.full_name} onChange={(e) => setForm((v) => ({ ...v, full_name: e.target.value }))} /></label><label className="field-label">Rol<select className="settings-role-select" value={form.role_code} onChange={(e) => setForm((v) => ({ ...v, role_code: e.target.value }))}>{roles.map((role) => <option key={role.id} value={role.code}>{role.name}</option>)}</select></label><button className="primary-button" type="submit">Invitar acceso</button></form><div className="portal-summary-grid"><article className="portal-summary-card"><span className="portal-summary-card__body"><small>Cuentas vinculadas</small><strong>{memberships.length}</strong></span></article><article className="portal-summary-card"><span className="portal-summary-card__body"><small>Invitaciones</small><strong>{invitations.length}</strong></span></article><article className="portal-summary-card"><span className="portal-summary-card__body"><small>Registros por revisar</small><strong>{registrations.filter((r) => r.status !== 'linked').length}</strong></span></article></div><div className="clients-table"><div className="clients-table__head"><span>Persona</span><span>Correo</span><span>Estado</span><span>Roles</span></div>{memberships.map((item) => <div className="clients-table__row" key={item.id}><span>{item.full_name}</span><span>{item.email}</span><span>{item.status}</span><span>{item.role_codes.join(', ')}</span></div>)}</div></section>;
}
