"""add quotation advisor

Revision ID: 917baf3a5378
Revises: c0fa71033b73
Create Date: 2026-06-17 13:15:44.403241
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '917baf3a5378'
down_revision: Union[str, None] = 'c0fa71033b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('advisor_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_quotations_advisor_id'), 'quotations', ['advisor_id'], unique=False)
    op.create_foreign_key(
        'quotations_advisor_id_fkey',
        'quotations',
        'users',
        ['advisor_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quotations_advisor_id_fkey', 'quotations', type_='foreignkey')
    op.drop_index(op.f('ix_quotations_advisor_id'), table_name='quotations')
    op.drop_column('quotations', 'advisor_id')
    # ### end Alembic commands ###
