"""add client portal configuration and invitations

Revision ID: bd2270bc5282
Revises: 120ab33b56f9
Create Date: 2026-08-04 15:41:39.204161
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "bd2270bc5282"
down_revision: Union[str, None] = "120ab33b56f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "client_portals",
        sa.Column(
            "client_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "display_name",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "logo_path",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "primary_color",
            sa.String(length=20),
            nullable=True,
        ),
        sa.Column(
            "language",
            sa.String(length=10),
            server_default="es-MX",
            nullable=False,
        ),
        sa.Column(
            "timezone",
            sa.String(length=80),
            server_default="America/Mexico_City",
            nullable=False,
        ),
        sa.Column(
            "default_home_page",
            sa.String(length=80),
            server_default="dashboard",
            nullable=False,
        ),
        sa.Column(
            "welcome_message",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "allow_self_registration",
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
        sa.Column(
            "allow_invitations",
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
        sa.Column(
            "require_mfa",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
        sa.Column(
            "session_timeout_minutes",
            sa.Integer(),
            server_default="480",
            nullable=False,
        ),
        sa.Column(
            "password_expiration_days",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "email_notifications_enabled",
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
        sa.Column(
            "is_enabled",
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
        sa.Column(
            "created_by",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "updated_by",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "deleted_by",
            sa.Integer(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name="fk_client_portals_client_id_clients",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_client_portals_created_by_users",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name="fk_client_portals_updated_by_users",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "client_id",
            name="uq_client_portal_client",
        ),
    )

    op.create_index(
        op.f("ix_client_portals_client_id"),
        "client_portals",
        ["client_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_client_portals_created_by"),
        "client_portals",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_portals_is_enabled"),
        "client_portals",
        ["is_enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_portals_updated_by"),
        "client_portals",
        ["updated_by"],
        unique=False,
    )

    op.create_table(
        "portal_invitations",
        sa.Column(
            "client_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "full_name",
            sa.String(length=180),
            nullable=True,
        ),
        sa.Column(
            "invited_by",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "token_hash",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "accepted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "cancelled_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "cancelled_by",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "revoked_by",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "accepted_user_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "resulting_membership_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "deleted_by",
            sa.Integer(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["accepted_user_id"],
            ["users.id"],
            name="fk_portal_invitations_accepted_user_id_users",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by"],
            ["users.id"],
            name="fk_portal_invitations_cancelled_by_users",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name="fk_portal_invitations_client_id_clients",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
            name="fk_portal_invitations_invited_by_users",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resulting_membership_id"],
            ["client_portal_memberships.id"],
            name="fk_portal_invitations_resulting_membership_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by"],
            ["users.id"],
            name="fk_portal_invitations_revoked_by_users",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_portal_invitations_accepted_user_id"),
        "portal_invitations",
        ["accepted_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portal_invitations_cancelled_by"),
        "portal_invitations",
        ["cancelled_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portal_invitations_client_id"),
        "portal_invitations",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portal_invitations_email"),
        "portal_invitations",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portal_invitations_expires_at"),
        "portal_invitations",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portal_invitations_invited_by"),
        "portal_invitations",
        ["invited_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portal_invitations_resulting_membership_id"),
        "portal_invitations",
        ["resulting_membership_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_portal_invitations_revoked_by"),
        "portal_invitations",
        ["revoked_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portal_invitations_status"),
        "portal_invitations",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portal_invitations_token_hash"),
        "portal_invitations",
        ["token_hash"],
        unique=True,
    )

    op.create_table(
        "portal_invitation_roles",
        sa.Column(
            "invitation_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "role_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invitation_id"],
            ["portal_invitations.id"],
            name="fk_portal_invitation_roles_invitation_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["client_portal_roles.id"],
            name="fk_portal_invitation_roles_role_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "invitation_id",
            "role_id",
            name="uq_portal_invitation_role",
        ),
    )

    op.create_index(
        op.f("ix_portal_invitation_roles_invitation_id"),
        "portal_invitation_roles",
        ["invitation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portal_invitation_roles_role_id"),
        "portal_invitation_roles",
        ["role_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        op.f("ix_portal_invitation_roles_role_id"),
        table_name="portal_invitation_roles",
    )
    op.drop_index(
        op.f("ix_portal_invitation_roles_invitation_id"),
        table_name="portal_invitation_roles",
    )
    op.drop_table("portal_invitation_roles")

    op.drop_index(
        op.f("ix_portal_invitations_token_hash"),
        table_name="portal_invitations",
    )
    op.drop_index(
        op.f("ix_portal_invitations_status"),
        table_name="portal_invitations",
    )
    op.drop_index(
        op.f("ix_portal_invitations_revoked_by"),
        table_name="portal_invitations",
    )
    op.drop_index(
        op.f("ix_portal_invitations_resulting_membership_id"),
        table_name="portal_invitations",
    )
    op.drop_index(
        op.f("ix_portal_invitations_invited_by"),
        table_name="portal_invitations",
    )
    op.drop_index(
        op.f("ix_portal_invitations_expires_at"),
        table_name="portal_invitations",
    )
    op.drop_index(
        op.f("ix_portal_invitations_email"),
        table_name="portal_invitations",
    )
    op.drop_index(
        op.f("ix_portal_invitations_client_id"),
        table_name="portal_invitations",
    )
    op.drop_index(
        op.f("ix_portal_invitations_cancelled_by"),
        table_name="portal_invitations",
    )
    op.drop_index(
        op.f("ix_portal_invitations_accepted_user_id"),
        table_name="portal_invitations",
    )
    op.drop_table("portal_invitations")

    op.drop_index(
        op.f("ix_client_portals_updated_by"),
        table_name="client_portals",
    )
    op.drop_index(
        op.f("ix_client_portals_is_enabled"),
        table_name="client_portals",
    )
    op.drop_index(
        op.f("ix_client_portals_created_by"),
        table_name="client_portals",
    )
    op.drop_index(
        op.f("ix_client_portals_client_id"),
        table_name="client_portals",
    )
    op.drop_table("client_portals")