import React, { useEffect, useState } from 'react';

import { getPortalCompanyInvitations, getPortalCompanyRoles, getPortalCompanyUsers, invitePortalCompanyUser, reactivatePortalCompanyUser, setPrimaryPortalCompanyUser, suspendPortalCompanyUser, updatePortalCompanyUserRoles } from '../../services/api.js';

export default function ClientPortalUsers({ permissions = [] }) {
  const [users, setUsers] = useState([]); const [invitations, setInvitations] = useState([]); const [roles, setRoles] = useState([]); const [form, setForm] = useState({ email: '', full_name: '', role_codes: ['viewer'] }); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const canInvite = permissions.includes('users.invite'); const canManage = permissions.includes('users.manage');
  async function load() { try { const [userItems, invitationItems, roleItems] = await Promise.all([getPortalCompanyUsers(), getPortalCompanyInvitations(), permissions.includes('roles.view') ? getPortalCompanyRoles() : []]); setUsers(userItems); setInvitations(invitationItems); setRoles(roleItems); setError(''); } catch (requestError) { setError(requestError.message); } }
  useEffect(() => { load(); }, []);
  async function action(work, message) { setError(''); try { await work(); setNotice(message); await load(); } catch (requestError) { setError(requestError.message); } }
  async function submit(event) { event.preventDefault(); return action(() => invitePortalCompanyUser({ ...form, full_name: form.full_name || null, notes: null }), 'Invitación creada.'); }
  function toggle(code) { setForm((current) => ({ ...current, role_codes: current.role_codes.includes(code) ? current.role_codes.filter((item) => item !== code) : [...current.role_codes, code] })); }
  return <section className="client-portal-page"><div className="client-portal-page__heading"><div><p>Organización</p><h1>Usuarios</h1><span>Cuentas e invitaciones de tu propia empresa.</span></div></div>{error ? <div className="portal-error">{error}</div> : null}{notice ? <div className="form-notice">{notice}</div> : null}
    {canInvite ? <form className="portal-user-invite" onSubmit={submit}><label>Correo<input required type="email" value={form.email} onChange={(event) => setForm((current) => ({ ...current, email: event.target.value }))} /></label><label>Nombre opcional<input value={form.full_name} onChange={(event) => setForm((current) => ({ ...current, full_name: event.target.value }))} /></label><div className="portal-role-options">{roles.map((role) => <label key={role.id}><input checked={form.role_codes.includes(role.code)} onChange={() => toggle(role.code)} type="checkbox" />{role.name}</label>)}</div><button className="primary-button" disabled={!form.role_codes.length} type="submit">Invitar</button></form> : null}
    <div className="portal-record-grid">{users.map((item) => <article className="portal-record-card" key={item.id}><div><strong>{item.full_name}{item.is_primary_contact ? ' · Principal' : ''}</strong><span>{item.email}</span><span>{item.status} · {item.role_codes.join(', ')}</span></div>{canManage ? <div className="portal-user-actions"><button disabled={item.is_primary_contact} onClick={() => action(() => setPrimaryPortalCompanyUser(item.id), 'Contacto principal actualizado.')} type="button">Marcar principal</button>{item.status === 'active' ? <button onClick={() => action(() => suspendPortalCompanyUser(item.id, 'Suspensión por administrador de la empresa'), 'Cuenta suspendida.')} type="button">Suspender</button> : <button onClick={() => action(() => reactivatePortalCompanyUser(item.id), 'Cuenta reactivada.')} type="button">Reactivar</button>}<details><summary>Cambiar roles</summary>{roles.map((role) => <label key={role.id}><input checked={item.role_codes.includes(role.code)} onChange={() => action(() => updatePortalCompanyUserRoles(item.id, item.role_codes.includes(role.code) ? item.role_codes.filter((code) => code !== role.code) : [...item.role_codes, role.code]), 'Roles actualizados.')} type="checkbox" />{role.name}</label>)}</details></div> : null}</article>)}</div>
    <section className="portal-invitation-summary"><h2>Invitaciones</h2>{invitations.map((item) => <p key={item.id}>{item.email} · {item.status} · {item.role_codes.join(', ')}</p>)}</section>
  </section>;
}
