INITIAL_ROLES = {
    "Administrador": "Acceso total al sistema.",
    "Comercial": "Gestion comercial, clientes y cotizaciones.",
    "Tecnico": "Gestion tecnica de equipos y hojas de campo.",
    "Captura": "Captura y generacion documental.",
    "Calidad": "Revision y aprobacion de certificados.",
    "Finanzas": "Pagos, facturacion y liberacion financiera.",
    "Cliente": "Acceso limitado para cliente externo.",
    "Desarrollador": "Acceso tecnico avanzado para desarrollo y soporte.",
    "Operador": "Opera resoluciones propias sin facultad de autorización.",
    "Auditor": "Consulta institucional de expedientes y evidencias.",
}

ACTIVITY_CONTRIBUTOR_PERMISSIONS = {
    "activity.read",
    "activity.create",
    "activity.edit_own",
    "activity.delete_own",
    "activity.attach_files",
    "activity.mention",
    "activity.request_attention",
    # Compatibilidad temporal con consumidores anteriores.
    "activity.write",
}

ACTIVITY_RESOLVER_PERMISSIONS = {
    *ACTIVITY_CONTRIBUTOR_PERMISSIONS,
    "activity.resolve_attention",
}

ACTIVITY_GOVERNANCE_PERMISSIONS = {
    *ACTIVITY_RESOLVER_PERMISSIONS,
    "activity.moderate",
    "activity.view_audit",
    "activity.audit",
}


ROLE_PERMISSIONS = {
    "Administrador": {"*"},
    "Comercial": {
        "resolution_center.read",
        *ACTIVITY_CONTRIBUTOR_PERMISSIONS,
        "clients.read",
        "clients.create",
        "clients.update",
        "catalog_items.read",
        "catalog_items.create",
        "catalog_items.update",
        "catalog_items.delete",
        "documents.read",
        "quotations.read",
        "quotations.create",
        "quotations.update",
        "quotations.act_as_advisor",
        "quotations.exceptions.request_change_service",
        "quotations.exceptions.apply_change_service",
        "quotations.exceptions.inspect_change_service",
        "quotations.exceptions.request_unlock",
        "quotations.exceptions.apply_unlock",
        "quotations.exceptions.inspect",
        "quotations.exceptions.rebuild_empty_service_order",
        "services.manage_service_type",
        "services.manage_linked_company",
        "services.manage_certificate_prefix",
        "service_orders.read",
        "service_orders.create",
        "service_orders.update",
        "service_orders.sales.manage",
        "service_orders.maintenance.manage",
        "service_orders.maintenance.sign",
        "service_orders.repair.manage",
        "service_orders.repair.sign",
        "service_orders.additional_equipment.propose",
        "service_orders.additional_equipment.commercial_review",
        "sat_catalogs.read",
        "sat_catalogs.manage_favorites",
        "sat_catalogs.manage_aliases",
    },
    "Tecnico": {
        "mobile.access",
        "resolution_center.read",
        *ACTIVITY_CONTRIBUTOR_PERMISSIONS,
        "equipment.read",
        "equipment.create",
        "equipment.update",
        "equipment.delete",
        "field_sheets.read",
        "field_sheets.create",
        "field_sheets.update",
        "field_sheets.review",
        "field_sheets.capture",
        "field_sheet_templates.read",
        "standards.read",
        "procedures.read",
        "documents.read",
        "document_interpretations.read",
        "technical_profiles.read",
        "reference_standard_certificates.read",
        "pattern_selection.execute",
        "uncertainty.execute",
        "operational_engines.execute",
        "service_orders.read",
        "service_orders.read_assigned",
        "service_orders.update",
        "service_orders.sign",
        "service_orders.read",
        "service_orders.additional_equipment.propose",
        "service_orders.additional_equipment.execute",
        "service_orders.sales.deliver",
        "service_orders.maintenance.execute",
        "service_orders.repair.execute",
        "lab_work_order_groups.create",
        "lab_work_orders.use",
        "lab_packages.download",
        "lab_clients.read",
        "lab_clients.create",
        "lab_clients.update",
        "tickets.create",
        "tickets.view_own",
    },
    "Captura": {
        "mobile.access",
        "resolution_center.read",
        *ACTIVITY_CONTRIBUTOR_PERMISSIONS,
        "clients.read",
        "quotations.read",
        "service_orders.read",
        "work_orders.read_organization",
        "lab_packages.download",
        "lab_clients.read",
        "lab_clients.create",
        "lab_clients.update",
        "lab_clients.deactivate",
        "tickets.create",
        "tickets.view_own",
        # Fase 3: permiso mínimo y exclusivo para capturar FieldSheets LAB una
        # vez que la recepción ya quedó firmada (received_signed/in_progress).
        # Deliberadamente NO se usa field_sheets.capture ni lab_work_orders.use
        # aquí: ambos códigos también habilitan endpoints de equipo/servicio/
        # cliente documental/cierre en el router LAB, y Captura no debe poder
        # crear OT, editar recepción, tocar equipo/servicio/folio ni firmar ni
        # cerrar administrativamente (ver ensure_lab_work_order_scope y los
        # gates de app/routers/lab_work_orders.py).
        "lab_field_sheets.capture",
        "field_sheets.read",
        "field_sheets.create",
        "field_sheets.update",
        "field_sheet_templates.read",
        "certificates.read",
        "certificates.create",
        "certificates.generate",
        "certificates.capture",
        "certificates.upload_pdf",
        "standards.read",
        "procedures.read",
        "documents.read",
        "document_interpretations.read",
        "technical_profiles.read",
        "reference_standard_certificates.read",
        "pattern_selection.execute",
        "uncertainty.execute",
        "operational_engines.execute",
    },
    "Calidad": {
        "resolution_center.read",
        *ACTIVITY_GOVERNANCE_PERMISSIONS,
        "audit_logs.read",
        "certificates.read",
        "certificates.quality",
        "certificates.approve",
        "certificates.match_override",
        "field_sheets.read",
        "field_sheets.update",
        "field_sheets.review",
        "service_orders.read",
        "service_orders.signatures.reopen",
        "service_orders.maintenance.manage",
        "service_orders.maintenance.execute",
        "service_orders.maintenance.authorize",
        "service_orders.maintenance.sign",
        "service_orders.maintenance.close",
        "service_orders.repair.manage",
        "service_orders.repair.execute",
        "service_orders.repair.authorize",
        "service_orders.repair.sign",
        "service_orders.repair.close",
        "tickets.view_own",
        "tickets.view_all",
        "tickets.review",
        "work_orders.reopen",
        "work_orders.reopen_preserve_signatures",
        "work_orders.reopen_invalidate_signatures",
        "service_orders.additional_equipment.authorize",
        "service_orders.administration.restore.authorize",
        "service_orders.administration.rebuild.authorize",
        "service_orders.administration.void.authorize",
        "standards.read",
        "procedures.read",
        "metrology.execute",
        "documents.read",
        "documents.create",
        "documents.update",
        "documents.approve",
        "documents.archive",
        "document_interpretations.read",
        "document_interpretations.create",
        "document_interpretations.update",
        "document_interpretations.approve",
        "technical_profiles.read",
        "technical_profiles.create",
        "technical_profiles.update",
        "technical_profiles.approve",
        "reference_standard_certificates.read",
        "reference_standard_certificates.create",
        "reference_standard_certificates.update",
        "reference_standard_certificates.approve",
        "reference_standard_certificates.delete",
        "pattern_selection.execute",
        "uncertainty.execute",
        "uncertainty_models.read",
        "uncertainty_models.create",
        "uncertainty_models.update",
        "uncertainty_models.approve",
        "uncertainty_models.exception",
        "field_sheet_templates.read",
        "field_sheet_templates.create",
        "field_sheet_templates.update",
        "field_sheet_templates.approve",
        "field_sheet_templates.archive",
        "field_sheet_templates.export",
        "field_sheet_templates.import",
        "settings.institutional.read",
        "settings.institutional.update",
        "operational_engines.execute",
    },
    "Finanzas": {
        "resolution_center.read",
        *ACTIVITY_RESOLVER_PERMISSIONS,
        "clients.read",
        "certificates.read",
        "quotations.read",
        "service_orders.read",
        "payments.read",
        "payments.manage",
        "invoices.read",
        "invoices.manage",
        "integrations.facturama.status",
        "certificates.release",
        "release.manage",
        "sat_catalogs.read",
        "sat_catalogs.manage_favorites",
        "sat_catalogs.manage_aliases",
    },
    "Cliente": {
        "portal.read",
        "quotations.read_own",
        "certificates.read_own",
        "service_orders.read_own",
        "service_orders.maintenance.sign",
        "service_orders.repair.sign",
    },
    "Desarrollador": {
        "mobile.access",
        "resolution_center.*",
        "service_orders.administration.restore.propose",
        "service_orders.administration.restore.authorize",
        "service_orders.administration.restore.execute",
        "service_orders.administration.rebuild.propose",
        "service_orders.administration.rebuild.authorize",
        "service_orders.administration.rebuild.execute",
        "service_orders.administration.void.propose",
        "service_orders.administration.void.authorize",
        "service_orders.administration.void.execute",
        "lab_work_orders.use",
        "lab_work_orders.export",
        "lab_work_orders.cancel",
        "lab_packages.download",
        "lab_clients.read",
        "lab_clients.create",
        "lab_clients.update",
        "lab_clients.import",
        "lab_clients.deactivate",
        "lab_work_order_groups.create",
        "lab_work_order_groups.requests.read",
        "lab_work_order_groups.requests.claim",
        "lab_work_order_groups.requests.decide",
        "tickets.create",
        "tickets.view_own",
        "tickets.view_all",
        "tickets.review",
        "work_orders.reopen",
        "work_orders.reopen_preserve_signatures",
        "work_orders.reopen_invalidate_signatures",
        *ACTIVITY_GOVERNANCE_PERMISSIONS,
        "audit_logs.read",
        "users.read",
        "users.manage",
        "settings.read",
        "settings.manage",
        "standards.read",
        "standards.create",
        "standards.update",
        "standards.delete",
        "procedures.read",
        "procedures.create",
        "procedures.update",
        "procedures.delete",
        "quotations.read",
        "quotations.update",
        "quotations.act_as_advisor",
        "quotations.exceptions.request_change_service",
        "quotations.exceptions.authorize_change_service",
        "quotations.exceptions.apply_change_service",
        "quotations.exceptions.inspect_change_service",
        "quotations.exceptions.request_unlock",
        "quotations.exceptions.authorize_unlock",
        "quotations.exceptions.apply_unlock",
        "quotations.exceptions.inspect",
        "quotations.exceptions.rebuild_empty_service_order",
        "services.manage_service_type",
        "services.manage_linked_company",
        "services.manage_certificate_prefix",
        "folios.manage_sequences",
        "metrology.execute",
        "documents.read",
        "documents.create",
        "documents.update",
        "documents.approve",
        "documents.archive",
        "document_interpretations.read",
        "document_interpretations.create",
        "document_interpretations.update",
        "document_interpretations.approve",
        "technical_profiles.read",
        "technical_profiles.create",
        "technical_profiles.update",
        "technical_profiles.approve",
        "reference_standard_certificates.read",
        "reference_standard_certificates.create",
        "reference_standard_certificates.update",
        "reference_standard_certificates.approve",
        "reference_standard_certificates.delete",
        "certificates.read",
        "certificates.create",
        "certificates.capture",
        "certificates.upload_pdf",
        "certificates.quality",
        "certificates.approve",
        "certificates.release",
        "release.manage",
        "certificates.match_override",
        "pattern_selection.execute",
        "uncertainty.execute",
        "uncertainty_models.read",
        "uncertainty_models.create",
        "uncertainty_models.update",
        "uncertainty_models.approve",
        "uncertainty_models.exception",
        "field_sheet_templates.read",
        "field_sheet_templates.create",
        "field_sheet_templates.update",
        "field_sheet_templates.approve",
        "field_sheet_templates.archive",
        "field_sheet_templates.export",
        "field_sheet_templates.import",
        "settings.system_parameters.read",
        "settings.system_parameters.update",
        "settings.master_catalogs.manage",
        "service_orders.read",
        "service_orders.sign",
        "service_orders.signatures.reopen",
        "service_orders.additional_equipment.propose",
        "service_orders.additional_equipment.authorize",
        "service_orders.additional_equipment.execute",
        "service_orders.additional_equipment.commercial_review",
        "service_orders.additional_equipment.audit",
        "service_orders.sales.manage",
        "service_orders.sales.deliver",
        "service_orders.sales.authorize",
        "service_orders.maintenance.manage",
        "service_orders.maintenance.execute",
        "service_orders.maintenance.authorize",
        "service_orders.maintenance.sign",
        "service_orders.maintenance.close",
        "service_orders.repair.manage",
        "service_orders.repair.execute",
        "service_orders.repair.authorize",
        "service_orders.repair.sign",
        "service_orders.repair.close",
        "sat_catalogs.read",
        "sat_catalogs.manage",
        "catalog_items.read",
        "catalog_items.create",
        "catalog_items.update",
        "catalog_items.delete",
        "clients.read",
        "clients.create",
        "clients.update",
        "equipment.read",
        "equipment.create",
        "equipment.update",
        "equipment.delete",
        "service_orders.create",
        "service_orders.update",
        "operational_engines.execute",
        "settings.institutional.read",
        "settings.institutional.update",
    },
    "Operador": {
        *ACTIVITY_CONTRIBUTOR_PERMISSIONS,
        "resolution_center.read",
        "resolution_center.create",
        "resolution_center.prepare",
        "resolution_center.analyze",
        "resolution_center.plan",
        "resolution_center.simulate",
        "resolution_center.execute",
        "service_orders.additional_equipment.propose",
        "service_orders.additional_equipment.execute",
        "service_orders.administration.restore.propose",
        "service_orders.administration.restore.execute",
        "service_orders.administration.rebuild.propose",
        "service_orders.administration.rebuild.execute",
        "service_orders.administration.void.propose",
        "service_orders.administration.void.execute",
    },
    "Auditor": {
        "activity.read",
        "activity.view_audit",
        "resolution_center.read",
        "resolution_center.read_all",
        "resolution_center.audit",
        "resolution_center.infrastructure",
        "audit_logs.read",
        "service_orders.additional_equipment.audit",
    },
}


PERMISSIONS = {
    "SERVICE_ORDERS_MAINTENANCE_MANAGE": "service_orders.maintenance.manage",
    "SERVICE_ORDERS_MAINTENANCE_EXECUTE": "service_orders.maintenance.execute",
    "SERVICE_ORDERS_MAINTENANCE_AUTHORIZE": "service_orders.maintenance.authorize",
    "SERVICE_ORDERS_MAINTENANCE_SIGN": "service_orders.maintenance.sign",
    "SERVICE_ORDERS_MAINTENANCE_CLOSE": "service_orders.maintenance.close",
    "SERVICE_ORDERS_REPAIR_MANAGE": "service_orders.repair.manage",
    "SERVICE_ORDERS_REPAIR_EXECUTE": "service_orders.repair.execute",
    "SERVICE_ORDERS_REPAIR_AUTHORIZE": "service_orders.repair.authorize",
    "SERVICE_ORDERS_REPAIR_SIGN": "service_orders.repair.sign",
    "SERVICE_ORDERS_REPAIR_CLOSE": "service_orders.repair.close",
    "SERVICE_ORDERS_DELETE": "service_orders.delete",
    "LAB_WORK_ORDERS_DELETE": "lab_work_orders.delete",
    "LAB_WORK_ORDER_GROUPS_CREATE": "lab_work_order_groups.create",
    "LAB_WORK_ORDER_GROUP_REQUESTS_READ": "lab_work_order_groups.requests.read",
    "LAB_WORK_ORDER_GROUP_REQUESTS_CLAIM": "lab_work_order_groups.requests.claim",
    "LAB_WORK_ORDER_GROUP_REQUESTS_DECIDE": "lab_work_order_groups.requests.decide",
    "TICKETS_CREATE": "tickets.create",
    "TICKETS_VIEW_OWN": "tickets.view_own",
    "TICKETS_VIEW_ALL": "tickets.view_all",
    "TICKETS_REVIEW": "tickets.review",
    "WORK_ORDERS_REOPEN": "work_orders.reopen",
    "WORK_ORDERS_REOPEN_PRESERVE_SIGNATURES": "work_orders.reopen_preserve_signatures",
    "WORK_ORDERS_REOPEN_INVALIDATE_SIGNATURES": "work_orders.reopen_invalidate_signatures",
    "ACTIVITY_READ": "activity.read",
    "ACTIVITY_CREATE": "activity.create",
    "ACTIVITY_EDIT_OWN": "activity.edit_own",
    "ACTIVITY_DELETE_OWN": "activity.delete_own",
    "ACTIVITY_MODERATE": "activity.moderate",
    "ACTIVITY_ATTACH_FILES": "activity.attach_files",
    "ACTIVITY_MENTION": "activity.mention",
    "ACTIVITY_REQUEST_ATTENTION": "activity.request_attention",
    "ACTIVITY_RESOLVE_ATTENTION": "activity.resolve_attention",
    "ACTIVITY_VIEW_AUDIT": "activity.view_audit",
    "USERS_READ": "users.read",
    "USERS_MANAGE": "users.manage",
    "CLIENTS_READ": "clients.read",
    "CLIENTS_CREATE": "clients.create",
    "CLIENTS_UPDATE": "clients.update",
    "CATALOG_ITEMS_READ": "catalog_items.read",
    "CATALOG_ITEMS_CREATE": "catalog_items.create",
    "CATALOG_ITEMS_UPDATE": "catalog_items.update",
    "CATALOG_ITEMS_DELETE": "catalog_items.delete",
    "QUOTATIONS_READ": "quotations.read",
    "QUOTATIONS_CREATE": "quotations.create",
    "QUOTATIONS_UPDATE": "quotations.update",
    "CERTIFICATES_READ": "certificates.read",
    "CERTIFICATES_CREATE": "certificates.create",
    "CERTIFICATES_APPROVE": "certificates.approve",
    "CERTIFICATES_CAPTURE": "certificates.capture",
    "CERTIFICATES_UPLOAD_PDF": "certificates.upload_pdf",
    "CERTIFICATES_MATCH_OVERRIDE": "certificates.match_override",
    "AUDIT_LOGS_READ": "audit_logs.read",
    "STANDARDS_READ": "standards.read",
    "STANDARDS_CREATE": "standards.create",
    "STANDARDS_UPDATE": "standards.update",
    "STANDARDS_DELETE": "standards.delete",
    "PROCEDURES_READ": "procedures.read",
    "PROCEDURES_CREATE": "procedures.create",
    "PROCEDURES_UPDATE": "procedures.update",
    "PROCEDURES_DELETE": "procedures.delete",
    "METROLOGY_EXECUTE": "metrology.execute",
    "OPERATIONAL_ENGINES_EXECUTE": "operational_engines.execute",
    "DOCUMENTS_READ": "documents.read",
    "DOCUMENTS_CREATE": "documents.create",
    "DOCUMENTS_UPDATE": "documents.update",
    "DOCUMENTS_APPROVE": "documents.approve",
    "DOCUMENTS_ARCHIVE": "documents.archive",
    "DOCUMENT_INTERPRETATIONS_READ": "document_interpretations.read",
    "DOCUMENT_INTERPRETATIONS_CREATE": "document_interpretations.create",
    "DOCUMENT_INTERPRETATIONS_UPDATE": "document_interpretations.update",
    "DOCUMENT_INTERPRETATIONS_APPROVE": "document_interpretations.approve",
    "TECHNICAL_PROFILES_READ": "technical_profiles.read",
    "TECHNICAL_PROFILES_CREATE": "technical_profiles.create",
    "TECHNICAL_PROFILES_UPDATE": "technical_profiles.update",
    "TECHNICAL_PROFILES_APPROVE": "technical_profiles.approve",
    "REFERENCE_STANDARD_CERTIFICATES_READ": "reference_standard_certificates.read",
    "REFERENCE_STANDARD_CERTIFICATES_CREATE": "reference_standard_certificates.create",
    "REFERENCE_STANDARD_CERTIFICATES_UPDATE": "reference_standard_certificates.update",
    "REFERENCE_STANDARD_CERTIFICATES_APPROVE": "reference_standard_certificates.approve",
    "REFERENCE_STANDARD_CERTIFICATES_DELETE": "reference_standard_certificates.delete",
    "PATTERN_SELECTION_EXECUTE": "pattern_selection.execute",
    "UNCERTAINTY_EXECUTE": "uncertainty.execute",
    "UNCERTAINTY_MODELS_READ": "uncertainty_models.read",
    "UNCERTAINTY_MODELS_CREATE": "uncertainty_models.create",
    "UNCERTAINTY_MODELS_UPDATE": "uncertainty_models.update",
    "UNCERTAINTY_MODELS_APPROVE": "uncertainty_models.approve",
    "UNCERTAINTY_MODELS_EXCEPTION": "uncertainty_models.exception",
    "FIELD_SHEET_TEMPLATES_READ": "field_sheet_templates.read",
    "FIELD_SHEET_TEMPLATES_CREATE": "field_sheet_templates.create",
    "FIELD_SHEET_TEMPLATES_UPDATE": "field_sheet_templates.update",
    "FIELD_SHEET_TEMPLATES_APPROVE": "field_sheet_templates.approve",
    "FIELD_SHEET_TEMPLATES_ARCHIVE": "field_sheet_templates.archive",
    "FIELD_SHEET_TEMPLATES_EXPORT": "field_sheet_templates.export",
    "FIELD_SHEET_TEMPLATES_IMPORT": "field_sheet_templates.import",
    "SETTINGS_SYSTEM_PARAMETERS_READ": "settings.system_parameters.read",
    "SETTINGS_SYSTEM_PARAMETERS_UPDATE": "settings.system_parameters.update",
    "SETTINGS_MASTER_CATALOGS_MANAGE": "settings.master_catalogs.manage",
    "SETTINGS_INSTITUTIONAL_READ": "settings.institutional.read",
    "SETTINGS_INSTITUTIONAL_UPDATE": "settings.institutional.update",
    "SERVICE_ORDERS_READ": "service_orders.read",
    "SERVICE_ORDERS_CREATE": "service_orders.create",
    "SERVICE_ORDERS_UPDATE": "service_orders.update",
    "SERVICE_ORDERS_SIGN": "service_orders.sign",
    "EQUIPMENT_READ": "equipment.read",
    "EQUIPMENT_CREATE": "equipment.create",
    "EQUIPMENT_UPDATE": "equipment.update",
    "EQUIPMENT_DELETE": "equipment.delete",
    "SERVICE_ORDERS_SIGNATURES_REOPEN": "service_orders.signatures.reopen",
    "SERVICE_ORDERS_ADDITIONAL_EQUIPMENT_PROPOSE": "service_orders.additional_equipment.propose",
    "SERVICE_ORDERS_ADDITIONAL_EQUIPMENT_AUTHORIZE": "service_orders.additional_equipment.authorize",
    "SERVICE_ORDERS_ADDITIONAL_EQUIPMENT_EXECUTE": "service_orders.additional_equipment.execute",
    "SERVICE_ORDERS_ADDITIONAL_EQUIPMENT_COMMERCIAL_REVIEW": "service_orders.additional_equipment.commercial_review",
    "SERVICE_ORDERS_ADDITIONAL_EQUIPMENT_AUDIT": "service_orders.additional_equipment.audit",
    "SERVICE_ORDERS_ADMIN_RESTORE_PROPOSE": "service_orders.administration.restore.propose",
    "SERVICE_ORDERS_ADMIN_RESTORE_AUTHORIZE": "service_orders.administration.restore.authorize",
    "SERVICE_ORDERS_ADMIN_RESTORE_EXECUTE": "service_orders.administration.restore.execute",
    "SERVICE_ORDERS_ADMIN_REBUILD_PROPOSE": "service_orders.administration.rebuild.propose",
    "SERVICE_ORDERS_ADMIN_REBUILD_AUTHORIZE": "service_orders.administration.rebuild.authorize",
    "SERVICE_ORDERS_ADMIN_REBUILD_EXECUTE": "service_orders.administration.rebuild.execute",
    "SERVICE_ORDERS_ADMIN_VOID_PROPOSE": "service_orders.administration.void.propose",
    "SERVICE_ORDERS_ADMIN_VOID_AUTHORIZE": "service_orders.administration.void.authorize",
    "SERVICE_ORDERS_ADMIN_VOID_EXECUTE": "service_orders.administration.void.execute",
    "SAT_CATALOGS_READ": "sat_catalogs.read",
    "SAT_CATALOGS_MANAGE": "sat_catalogs.manage",
    "SAT_CATALOGS_MANAGE_FAVORITES": "sat_catalogs.manage_favorites",
    "SAT_CATALOGS_MANAGE_ALIASES": "sat_catalogs.manage_aliases",
    "RESOLUTION_CENTER_READ": "resolution_center.read",
    "RESOLUTION_CENTER_READ_ALL": "resolution_center.read_all",
    "RESOLUTION_CENTER_CREATE": "resolution_center.create",
    "RESOLUTION_CENTER_PREPARE": "resolution_center.prepare",
    "RESOLUTION_CENTER_ANALYZE": "resolution_center.analyze",
    "RESOLUTION_CENTER_PLAN": "resolution_center.plan",
    "RESOLUTION_CENTER_SIMULATE": "resolution_center.simulate",
    "RESOLUTION_CENTER_AUTHORIZE": "resolution_center.authorize",
    "RESOLUTION_CENTER_EXECUTE": "resolution_center.execute",
    "RESOLUTION_CENTER_AUDIT": "resolution_center.audit",
    "RESOLUTION_CENTER_INFRASTRUCTURE": "resolution_center.infrastructure",
}
