INITIAL_ROLES = {
    "Administrador": "Acceso total al sistema.",
    "Comercial": "Gestion comercial, clientes y cotizaciones.",
    "Tecnico": "Gestion tecnica de equipos y hojas de campo.",
    "Captura": "Captura y generacion documental.",
    "Calidad": "Revision y aprobacion de certificados.",
    "Finanzas": "Pagos, facturacion y liberacion financiera.",
    "Cliente": "Acceso limitado para cliente externo.",
    "Desarrollador": "Acceso tecnico avanzado para desarrollo y soporte.",
}


ROLE_PERMISSIONS = {
    "Administrador": {"*"},
    "Comercial": {
        "clients.read",
        "clients.create",
        "clients.update",
        "documents.read",
        "quotations.read",
        "quotations.create",
        "quotations.update",
        "service_orders.read",
    },
    "Tecnico": {
        "equipment.read",
        "equipment.update",
        "field_sheets.read",
        "field_sheets.create",
        "field_sheets.update",
        "standards.read",
        "procedures.read",
        "documents.read",
        "document_interpretations.read",
        "technical_profiles.read",
        "reference_standard_certificates.read",
        "pattern_selection.execute",
        "service_orders.read",
        "service_orders.update",
    },
    "Captura": {
        "clients.read",
        "quotations.read",
        "service_orders.read",
        "field_sheets.read",
        "certificates.read",
        "certificates.create",
        "certificates.generate",
        "standards.read",
        "procedures.read",
        "documents.read",
        "document_interpretations.read",
        "technical_profiles.read",
        "reference_standard_certificates.read",
        "pattern_selection.execute",
    },
    "Calidad": {
        "certificates.read",
        "certificates.quality",
        "certificates.approve",
        "certificates.release",
        "field_sheets.read",
        "service_orders.read",
        "standards.read",
        "procedures.read",
        "metrology.execute",
        "documents.read",
        "documents.create",
        "documents.update",
        "documents.approve",
        "documents.archive",
        "document_interpretations.read",
        "document_interpretations.create",
        "document_interpretations.update",
        "document_interpretations.approve",
        "technical_profiles.read",
        "technical_profiles.create",
        "technical_profiles.update",
        "technical_profiles.approve",
        "reference_standard_certificates.read",
        "reference_standard_certificates.create",
        "reference_standard_certificates.update",
        "reference_standard_certificates.approve",
        "pattern_selection.execute",
    },
    "Finanzas": {
        "clients.read",
        "quotations.read",
        "payments.read",
        "payments.manage",
        "invoices.read",
        "invoices.manage",
        "release.manage",
    },
    "Cliente": {
        "portal.read",
        "quotations.read_own",
        "certificates.read_own",
        "service_orders.read_own",
    },
    "Desarrollador": {
        "audit_logs.read",
        "users.read",
        "users.manage",
        "settings.read",
        "settings.manage",
        "standards.read",
        "standards.create",
        "standards.update",
        "standards.delete",
        "procedures.read",
        "procedures.create",
        "procedures.update",
        "procedures.delete",
        "metrology.execute",
        "documents.read",
        "documents.create",
        "documents.update",
        "documents.approve",
        "documents.archive",
        "document_interpretations.read",
        "document_interpretations.create",
        "document_interpretations.update",
        "document_interpretations.approve",
        "technical_profiles.read",
        "technical_profiles.create",
        "technical_profiles.update",
        "technical_profiles.approve",
        "reference_standard_certificates.read",
        "reference_standard_certificates.create",
        "reference_standard_certificates.update",
        "reference_standard_certificates.approve",
        "pattern_selection.execute",
    },
}


PERMISSIONS = {
    "USERS_READ": "users.read",
    "USERS_MANAGE": "users.manage",
    "CLIENTS_READ": "clients.read",
    "CLIENTS_CREATE": "clients.create",
    "CLIENTS_UPDATE": "clients.update",
    "QUOTATIONS_READ": "quotations.read",
    "QUOTATIONS_CREATE": "quotations.create",
    "QUOTATIONS_UPDATE": "quotations.update",
    "CERTIFICATES_READ": "certificates.read",
    "CERTIFICATES_CREATE": "certificates.create",
    "CERTIFICATES_APPROVE": "certificates.approve",
    "AUDIT_LOGS_READ": "audit_logs.read",
    "STANDARDS_READ": "standards.read",
    "STANDARDS_CREATE": "standards.create",
    "STANDARDS_UPDATE": "standards.update",
    "STANDARDS_DELETE": "standards.delete",
    "PROCEDURES_READ": "procedures.read",
    "PROCEDURES_CREATE": "procedures.create",
    "PROCEDURES_UPDATE": "procedures.update",
    "PROCEDURES_DELETE": "procedures.delete",
    "METROLOGY_EXECUTE": "metrology.execute",
    "DOCUMENTS_READ": "documents.read",
    "DOCUMENTS_CREATE": "documents.create",
    "DOCUMENTS_UPDATE": "documents.update",
    "DOCUMENTS_APPROVE": "documents.approve",
    "DOCUMENTS_ARCHIVE": "documents.archive",
    "DOCUMENT_INTERPRETATIONS_READ": "document_interpretations.read",
    "DOCUMENT_INTERPRETATIONS_CREATE": "document_interpretations.create",
    "DOCUMENT_INTERPRETATIONS_UPDATE": "document_interpretations.update",
    "DOCUMENT_INTERPRETATIONS_APPROVE": "document_interpretations.approve",
    "TECHNICAL_PROFILES_READ": "technical_profiles.read",
    "TECHNICAL_PROFILES_CREATE": "technical_profiles.create",
    "TECHNICAL_PROFILES_UPDATE": "technical_profiles.update",
    "TECHNICAL_PROFILES_APPROVE": "technical_profiles.approve",
    "REFERENCE_STANDARD_CERTIFICATES_READ": "reference_standard_certificates.read",
    "REFERENCE_STANDARD_CERTIFICATES_CREATE": "reference_standard_certificates.create",
    "REFERENCE_STANDARD_CERTIFICATES_UPDATE": "reference_standard_certificates.update",
    "REFERENCE_STANDARD_CERTIFICATES_APPROVE": "reference_standard_certificates.approve",
    "PATTERN_SELECTION_EXECUTE": "pattern_selection.execute",
}
